In [5]:
from datasets import load_from_disk
import torch

/usr/local/lib/python3.11/dist-packages/tqdm/auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm


In [6]:
train_dir=rf'/hy-tmp/data/sample_0.2/train_dataset'

In [7]:
train_data=load_from_disk(train_dir)

In [8]:
print(train_data)

Dataset({
    features: ['image', 'spectrum', 'params', 'z'],
    num_rows: 57797
})


In [12]:
def get_mean_std(train_data):
    """Calculate mean and std of training dataset."""
    # 获取所有图像张量并堆叠
    all_images = [sample['image'] for sample in train_data]
    # 堆叠为 (N, 5, 64, 64) 的张量
    images_tensor = torch.stack(all_images)
    print(images_tensor.shape)

    # 计算通道维度(0)的均值和标准差(保留小数点后三位)
    mean = images_tensor.mean(dim=[0, 2, 3]).tolist()
    std = images_tensor.std(dim=[0, 2, 3]).tolist()

    return mean, std

In [13]:
mean, std=get_mean_std(train_data)

torch.Size([57797, 5, 64, 64])


In [16]:
print(mean)
print(std)

[0.003893157234415412, 0.005610359832644463, 0.008612471632659435, 0.012269098311662674, 0.01978866569697857]
[0.419291228055954, 0.26958438754081726, 0.37643587589263916, 0.47876837849617004, 1.3251533508300781]


In [17]:
mean_rounded = [round(m, 3) for m in mean]
std_rounded = [round(s, 3) for s in std]

# 打印结果
print("Rounded Mean:", mean_rounded)
print("Rounded Std:", std_rounded)

Rounded Mean: [0.004, 0.006, 0.009, 0.012, 0.02]
Rounded Std: [0.419, 0.27, 0.376, 0.479, 1.325]


In [10]:
#写一个统计一下所有图片的像素值的范围
def get_pixel_range(train_data):
    """Calculate min and max pixel values for each channel across all images."""
    min_val = float('inf')
    max_val = float('-inf')

    for sample in train_data:
        image_tensor = sample['image'].numpy()  # (5, 64, 64)
        current_min = image_tensor.min().item()
        current_max = image_tensor.max().item()

        if current_min < min_val:
            min_val = current_min
        if current_max > max_val:
            max_val = current_max

    return min_val, max_val

In [11]:
min_val, max_val=get_pixel_range(train_data)

In [15]:
print(min_val)
print(max_val)

-8.609375
2032.0


In [21]:
x=torch.randn(2,3,2,2)
print(x)

tensor([[[[-1.2283,  1.2263],
          [-1.6526, -0.1259]],

         [[ 1.5521, -0.7314],
          [ 0.2407, -1.9510]],

         [[ 1.3873, -0.9966],
          [ 0.3408, -0.2682]]],


        [[[-0.2511, -0.9092],
          [ 0.4918,  0.1290]],

         [[-0.8625, -0.2328],
          [-0.3678, -1.2051]],

         [[ 0.7374, -0.8151],
          [-0.0771, -1.6387]]]])


In [23]:
x.min()

tensor(-1.9510)

In [24]:
print(train_data)

Dataset({
    features: ['image', 'spectrum', 'params', 'z'],
    num_rows: 57797
})


In [25]:
print(f"像素值范围:{train_data['image'].min()}-{train_data['image'].max()}")

像素值范围:-8.609375-2032.0


In [26]:
min=-8.609375

In [28]:
round(min,3)

-8.609

In [29]:
round(2032.0,3)

2032.0

In [36]:
def min_max(x):
    x=x.numpy()
    min=round(-8.609375,3)
    max=round(2032.0,3)
    x=(x-min)/(max-min)
    x=torch.from_numpy(x)
    return x

In [31]:
train_data_100=train_data.select(range(100))
print(train_data_100)

Dataset({
    features: ['image', 'spectrum', 'params', 'z'],
    num_rows: 100
})


In [38]:
train_data_100['image']

tensor([[[[-4.2114e-03,  3.4790e-02, -1.7212e-02,  ..., -1.7273e-02,
            7.4219e-02, -5.6519e-02],
          [-8.2153e-02, -5.6152e-02,  6.0791e-02,  ...,  4.8035e-02,
           -3.0365e-02,  7.4219e-02],
          [ 6.0791e-02,  2.1790e-02, -6.9214e-02,  ..., -3.0334e-02,
           -4.2267e-03,  2.1912e-02],
          ...,
          [-4.2267e-03, -4.3213e-02,  8.7738e-03,  ..., -6.9580e-02,
            4.8035e-02, -3.0365e-02],
          [ 2.1759e-02,  7.3730e-02,  8.7738e-03,  ..., -1.7303e-02,
           -3.0365e-02,  7.4219e-02],
          [-5.6213e-02,  6.0730e-02,  8.7738e-03,  ...,  2.1881e-02,
           -6.9580e-02, -4.3457e-02]],

         [[ 2.4605e-03, -1.0010e-02, -1.4160e-02,  ..., -5.9509e-03,
           -1.7910e-03, -5.9509e-03],
          [ 1.4923e-02,  6.6071e-03, -1.4160e-02,  ...,  1.4847e-02,
            1.0681e-02,  6.5231e-03],
          [-2.2461e-02,  1.0757e-02,  2.3224e-02,  ..., -1.7891e-03,
           -1.7910e-03, -1.4267e-02],
          ...,
     

In [42]:
image=train_data_100['image']
print(image.shape)

torch.Size([100, 5, 64, 64])


In [50]:
print(f"范围:{image.min().item()}-{image.max().item()}")
image_mm=(image-image.min())/(image.max()-image.min())
print(f"范围:{image_mm.min().item()}-{image_mm.max().item()}")

范围:-1.0234375-40.875
范围:0.0-1.0


In [48]:
image.mean()

tensor(0.0083)

In [1]:
from dataset_util.PairDataset import PairDataset
from torchvision.transforms import transforms

train_transform = transforms.Compose([
    transforms.Normalize(mean=[0.004, 0.006, 0.009, 0.012, 0.02], std=[0.419, 0.27, 0.376, 0.479, 1.325])

])
# 准备训练数据
train_dataset = PairDataset(train_data, transform=train_transform)

NameError: name 'train_data' is not defined

In [11]:
import torch
x=torch.randn(2,5,2,2)

In [20]:
mean=x.mean(dim=[0,2,3],keepdim=True)
std=x.std(dim=[0,2,3],keepdim=True)
print(mean)
print(std)

tensor([[[[-0.1385]],

         [[-0.1737]],

         [[ 0.2128]],

         [[ 0.3827]],

         [[ 0.1552]]]])
tensor([[[[1.3333]],

         [[1.1309]],

         [[0.4829]],

         [[0.9988]],

         [[0.9189]]]])


In [21]:
x_norm=(x-mean)/std
print(x_norm)

tensor([[[[-0.2144,  0.6997],
          [-0.3193,  1.0845]],

         [[-0.1819, -0.2438],
          [-0.7928, -0.8023]],

         [[ 1.6241,  0.1198],
          [-0.1928, -0.4482]],

         [[ 1.3573, -0.3468],
          [-1.1404,  0.0042]],

         [[ 1.2426, -1.7029],
          [ 0.3117, -0.2576]]],


        [[[-0.7617, -1.3884],
          [ 1.5161, -0.6164]],

         [[-0.7402, -0.3020],
          [ 1.9222,  1.1408]],

         [[-1.6775,  1.0726],
          [-0.1451, -0.3528]],

         [[ 1.5293, -0.6145],
          [-0.9900,  0.2010]],

         [[ 1.0893,  0.5126],
          [-0.9357, -0.2600]]]])


In [22]:
x_mm=(x-x.min())/(x.max()-x.min())
print(f"{x_mm.min()}-{x_mm.max()}")

0.0-1.0


In [24]:
mean_mm=x_mm.mean(dim=[0,2,3],keepdim=True)
std_mm=x_mm.std(dim=[0,2,3],keepdim=True)
print(mean_mm)
print(std_mm)

tensor([[[[0.4640]],

         [[0.4552]],

         [[0.5520]],

         [[0.5946]],

         [[0.5376]]]])
tensor([[[[0.3342]],

         [[0.2834]],

         [[0.1210]],

         [[0.2503]],

         [[0.2303]]]])


In [25]:
x_mm_norm=(x_mm-mean_mm)/std_mm
print(x_mm_norm)

tensor([[[[-0.2144,  0.6997],
          [-0.3193,  1.0845]],

         [[-0.1819, -0.2438],
          [-0.7928, -0.8023]],

         [[ 1.6241,  0.1198],
          [-0.1928, -0.4482]],

         [[ 1.3573, -0.3468],
          [-1.1404,  0.0042]],

         [[ 1.2426, -1.7029],
          [ 0.3117, -0.2576]]],


        [[[-0.7617, -1.3884],
          [ 1.5161, -0.6164]],

         [[-0.7402, -0.3020],
          [ 1.9222,  1.1408]],

         [[-1.6775,  1.0726],
          [-0.1451, -0.3528]],

         [[ 1.5293, -0.6145],
          [-0.9900,  0.2010]],

         [[ 1.0893,  0.5126],
          [-0.9357, -0.2600]]]])


In [26]:
x_mm_norm==x_norm

tensor([[[[False, False],
          [False,  True]],

         [[False, False],
          [False,  True]],

         [[False, False],
          [False, False]],

         [[False, False],
          [ True, False]],

         [[False, False],
          [False, False]]],


        [[[False, False],
          [False, False]],

         [[ True, False],
          [False,  True]],

         [[False, False],
          [False, False]],

         [[ True, False],
          [ True, False]],

         [[False,  True],
          [False,  True]]]])